language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t k8s/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t k8s/client npm run test -- --coverages

