language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t k8s/client -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true -t k8s/client npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "K8sDocker"
  environment: "K8sdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-908665615728"
  bucket_path: "K8sDocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
